// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIN_IcGE5ImTOf9JwMB-Gz8ZTQx3gY5Ic',
    appId: '1:631986204393:web:3c8ff96ccd9fa7456e4a78',
    messagingSenderId: '631986204393',
    projectId: 'colicontas-5cd5a',
    authDomain: 'colicontas-5cd5a.firebaseapp.com',
    storageBucket: 'colicontas-5cd5a.appspot.com',
    measurementId: 'G-WFPKWKVY7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_eVqSr3etO1Td0NNE6N25XRk1PptvBf8',
    appId: '1:631986204393:android:fcc7da9e708eb1876e4a78',
    messagingSenderId: '631986204393',
    projectId: 'colicontas-5cd5a',
    storageBucket: 'colicontas-5cd5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwzd2pSAO6hGvcWmzuhSYmEm4sfi1otvU',
    appId: '1:631986204393:ios:623a4727d412f83a6e4a78',
    messagingSenderId: '631986204393',
    projectId: 'colicontas-5cd5a',
    storageBucket: 'colicontas-5cd5a.appspot.com',
    iosClientId: '631986204393-79l6sudg279e5lf5ntp2mhgcu06ciud8.apps.googleusercontent.com',
    iosBundleId: 'com.example.coliscontas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwzd2pSAO6hGvcWmzuhSYmEm4sfi1otvU',
    appId: '1:631986204393:ios:623a4727d412f83a6e4a78',
    messagingSenderId: '631986204393',
    projectId: 'colicontas-5cd5a',
    storageBucket: 'colicontas-5cd5a.appspot.com',
    iosClientId: '631986204393-79l6sudg279e5lf5ntp2mhgcu06ciud8.apps.googleusercontent.com',
    iosBundleId: 'com.example.coliscontas',
  );
}
